#!/bin/bash -e

fork() {
    echo [fork] $1 ...
    local ppath=../$1
    mkdir -v $ppath
    cd $ppath
    cp -r ../ejoy2d . 
    cd ejoy2d/android && make create && cd ../..
    git init
    git remote add origin git@git.oschina.net:lvshaco/$1.git
    git pull origin master
    git submodule add git@github.com:lvshaco/ejoy2d.git
    cp ejoy2d/shaco-foot .   
    cp ejoy2d/android/AndroidManifest.xml .
    git add shaco-foot
    git add AndroidManifest.xml
    git commit -a -m "shaco-foot fork"
    git push origin master
    echo [fork] $1 ok
}

an() {
    shift
    if [ $1 == "update" ]; then
        echo test
        cp AndroidManifest.xml ejoy2d/android
    fi
    cd ejoy2d/android && make $@
}

USAGE="Usage:./shaco-foot
    * fork       project_name
    * android    op\n"

case "$1" in
fork) shift; fork "$@";;
android) shift; an "$@";;
*) printf "$USAGE";;
esac
